Online Shopping Application/Controllers/UserLoginController.cs
namespace Online_Shopping_Application.Controllers
{
    public class UserLoginController : Controller
    {

        private readonly IConfiguration _configuration;
        private readonly HttpAPIWrapper _apiWrapper;

        public UserLoginController(IConfiguration configuration, HttpAPIWrapper apiWrapper)
        {
            _configuration = configuration;
            _apiWrapper = apiWrapper;
        }

        public IActionResult Login()
            {
            return View();
        }
        [HttpPost]
       
        public async Task<IActionResult> LoginIn(string username, string password)
        {
            var endpoint = Constants.APIEndpoints.Login;
            var content = new LoginAPIModel
            {
                Username = username,
                Password = password
            };

            var response = await _apiWrapper.PostAsync<TokenResponse, LoginAPIModel>(endpoint, content);

            if (response.IsSuccess)
            {
                var tokenData = response.data;

                // Parse the token
                var tokenHandler = new JwtSecurityTokenHandler();

                // Validate the token
                var tokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    ValidateAudience = true,
                    ValidateIssuerSigningKey = true,
                    ValidIssuer = _configuration.GetValue<string>("JWT:Issuer"),
                    ValidAudience = _configuration.GetValue<string>("JWT:Audience"),
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration.GetValue<string>("JWT:Key")))
                };

                SecurityToken validatedToken;
                var principal = tokenHandler.ValidateToken(tokenData.Token, tokenValidationParameters, out validatedToken);

               
                var userId = principal.FindFirst(ClaimTypes.Name)?.Value;
                var userRole = principal.FindFirst(ClaimTypes.Role)?.Value;
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                

                return RedirectToAction("Index", "Dashboard");
            }
            else
            {

                ViewBag.ErrorMessage = "Invalid username or password";
                return View("Login");
            }
        }


       
        public IActionResult Registration()
        {
            return View();
        }
    }
}

Online Shopping Application/Views/UserLogin/Login.cshtml
@model Online_Shopping_Application.Models.LoginAPIModel

<section class="vh-60" style="background-color: #df5b5b;">
    <div class="container py-5 h-60">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-6">
                <div class="card" style="border-radius: 1rem;">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                                 alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">

                                <form asp-controller="UserLogin" asp-action="LogIn" method="post">
                                    <div class="d-flex align-items-center mb-3 pb-1">
                                        <span class="text-primary">
                                            <i class="bi bi-cube"></i>
                                        </span>
                                        <span class="h1 fw-bold mb-0">Logo</span>
                                    </div>

                                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>

                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label"></label>
                                        <input type="email" name="username" class="form-control" placeholder="Enter your username">
                                    </div>

                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label"> </label>
                                        <input type="password" name="Password" class="form-control" placeholder="Enter your password">
                                    </div>

                                    <div class="pt-1 mb-4">
                                        <button class="btn btn-danger btn-lg btn-block" type="submit">Login</button>
                                    </div>

                                    <a class="small text-muted" href="#!">Forgot password?</a>
                                    <p class="mb-5 pb-lg-2" style="color: #393f81;">
                                        Don't have an account? <a href="#!" style="color: #393f81;">Register here</a>
                                    </p>
                                    <a href="#!" class="small text-muted">Terms of use.</a>
                                    <a href="#!" class="small text-muted">Privacy policy</a>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Online Shopping Application/Views/UserLogin/Registration.cshtml
@model Online_Shopping_Application.Models.RegisterAPIModel

<section class="vh-60" style="background-color:#df5b5b;">
    <div class="container py-5 h-60">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-6">
                <div class="card" style="border-radius: 1rem;">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                                 alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">

                                <form>

                                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">SignUp your account</h5>

                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label"></label>
                                        <input type="text" name="username" class="form-control" placeholder="Enter your username">
                                    </div>

                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label"></label>
                                        <input type="email" name="Email" class="form-control" placeholder="Enter your email">
                                    </div>

                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label"></label>
                                        <input type="password" name="Password" class="form-control" placeholder="Enter your password">
                                    </div>

                                    <div class="input-group input-group-outline my-3">
                                        <label class="form-label"></label>
                                        <input type="text" name="PhoneNumber" class="form-control" placeholder="Enter your phone number">
                                    </div>

                                    <!-- Submit button -->
                                    <div class="pt-1 mb-4">
                                        <button class="btn btn-danger btn-lg btn-block" type="submit">SignUp</button>
                                    </div>

                                    @*  <!-- Register buttons -->
                                    <div class="text-center">
                                    <p>or sign up with:</p>
                                    <button type="button" class="btn btn-link btn-floating mx-1">
                                    <i class="fab fa-facebook-f"></i>
                                    </button>

                                    <button type="button" class="btn btn-link btn-floating mx-1">
                                    <i class="fab fa-google"></i>
                                    </button>

                                    <button type="button" class="btn btn-link btn-floating mx-1">
                                    <i class="fab fa-twitter"></i>
                                    </button>

                                    <button type="button" class="btn btn-link btn-floating mx-1">
                                    <i class="fab fa-github"></i>
                                    </button>
                                    </div> *@

                                    <a href="#!" class="small text-muted">Terms of use.</a>
                                    <a href="#!" class="small text-muted">Privacy policy</a>
                                </form>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>